### ISSUE TITLE
Some engine bugs with SWE and Waterfall Restock

### ISSUE THREAD

**Issue by ArgentGamer** [ensou04/RocketSoundEnhancementDefault#5]
(Tested by setting external to 0% and with both SWE and Waterfall Restock together) Engines that don't have their Waterfall/Stock sounds removed are: All jet engines except Rapier when in closed cycle mode, All SRBs, Spark, Vector, Skiff, Skipper, Mammoth, and Rhino. It seems that the last 6 engines are listed in the WaterfallRestock_overrides in StockWaterfallEffects\Mod Configurations\ReStock, it can probably be fixed by making a config for it. As for the Jet engines and the SRBs, I have no idea.

**Comment by JonnyOThan** [comment]
Hi @ArgentGamer can you please post your ksp.log file?

**Comment by ArgentGamer** [comment]
[KSP.log](https://github.com/user-attachments/files/16569375/KSP.log)
[Player.log](https://github.com/user-attachments/files/16569376/Player.log)

Sorry for not posting it sooner, but here.

**Comment by likeproblem** [comment]
The issue is, looks like the patch for SWE does not remove jet sounds, I made a little cfg which does it for it, I am still not sure why SRB also do that, I might look into it, but I never heard problems about these six engines. I will try to find that cfg and send it to you, if you want

**Comment by likeproblem** [comment]
I am not sure what happened to SRBs and engines, but AUDIO node can be deleted as usual, I might try it and say what happens

**Comment by likeproblem** [comment]
Hmm, about engines it's Waterfall Restock, which I don't use sadly

**Comment by likeproblem** [comment]
here it is
[RSEFixes.cfg.txt](https://github.com/user-attachments/files/16971650/RSEFixes.cfg.txt)

SRBs still act weird, sometimes mute, sometimes not, but good enough
obviosly remove .txt

**Comment by likeproblem** [comment]
Shit, those 6 engines mentioned also hate me... I will try my best and figure out(even if nobody reads me and I will be forgotten lol)

**Comment by likeproblem** [comment]
I figured it out. Dis bastards use LAST, which means nothing can stop then, unless we use the same method MUHAHAHA

**Comment by likeproblem** [comment]
[RSEFixes.cfg.txt](https://github.com/user-attachments/files/17000757/RSEFixes.cfg.txt)
fix fix fix

**Comment by ArgentGamer** [comment]
> [RSEFixes.cfg.txt](https://github.com/user-attachments/files/17000757/RSEFixes.cfg.txt) fix fix fix

Can confirm this fixed the issues for me, on everything I mentioned. This should be added

**Comment by likeproblem** [comment]
Glad it helped :)
